spring:
  profiles:
    active:
      - dog
      - EN
      - prod
guru:
  username: YMLUser
  password: YMLPass
  jdbcurl: YmlUrl

---
spring:
  profile: prod
guru:
  username: ProdYMLUser
  password: ProdYMLPass
  jdbcurl: ProdYmlUrl
